url: '' # the base hostname & protocol for your site, e.g. http://example.com
baseurl: '' # the subpath of your site, e.g. /blog
title: CushyStudio blog
# email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
    A blog for CushyStudio related news.
github_username: rvion
# Build settings
theme: minima
plugins:
    - jekyll-feed
